const MASK_DAY_MONTH_YEAR_DOTS = "dd'.'mm'.'yyyy";
const MASK_DAY_MONTH_SHORT_YEAR_DOTS_HOUR_MINUTE = "dd'.'mm'.'yy' 'HH':'MM";

export { MASK_DAY_MONTH_YEAR_DOTS, MASK_DAY_MONTH_SHORT_YEAR_DOTS_HOUR_MINUTE };
